apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m9rv1xjbj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m9rv1xjbj-python 
  name: m9rv1xjbj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: m9rv1xjbj-python 
